# Exported from Render on 2025-05-24T14:00:58Z
services:
- type: web
  name: currency_exchange
  runtime: python
  repo: https://github.com/CHSevero/currency_exchange
  plan: free
  region: virginia
  env:
    - key: PYTHON_VERSION
      value: "3.13.0"
  buildCommand: curl -LsSf https://astral.sh/uv/install.sh | sh && $HOME/.local/bin/uv pip install -e .
  startCommand: $HOME/.local/bin/uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
  autoDeployTrigger: commit
  rootDir: .
version: "1"

