# Exported from Render on 2025-05-24T14:00:58Z
services:
- type: web
  name: currency_exchange
  runtime: python
  repo: https://github.com/CHSevero/currency_exchange
  plan: free
  region: virginia
  buildCommand: |
    export PATH="$HOME/.local/bin:$PATH"
    curl -LsSf https://astral.sh/uv/install.sh | sh
    source $HOME/.local/bin/env
    uv pip install -e .
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
  autoDeployTrigger: commit
  rootDir: .
version: "1"

